<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class TeacherProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample teacher profile data (10 teachers)
        $teachers = [
            [
                'first_name' => 'Mary Jane',
                'last_name' => 'Santos',
                'email' => 'mary.santos@example.com',
                'gender' => 'Female',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
                'biography' => 'Majored in English Literature and hold a TESOL certification. I specialize in making lessons engaging and easy to understand for beginners.',
                'point_consumed' => 100,
                'career' => 'Online ESL Instructor (4 years)',
                'graduation_school' => 'University of the Philippines',
                'certification' => 'TESOL, TEYL',
                'about_me' => 'I love traveling and watching movies. Let us enjoy learning English together in a fun, relaxed atmosphere!',
                'specialty' => 'Daily English, Callan Method, Kids English',
                'rating_average' => 4.95,
            ],
            [
                'first_name' => 'John Patrick',
                'last_name' => 'Reyes',
                'email' => 'john.reyes@example.com',
                'gender' => 'Male',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400',
                'biography' => 'Focusing on Business English and practical expressions for professional settings. Highly experienced in accent and pronunciation coaching.',
                'point_consumed' => 120,
                'career' => 'Global BPO Corporate Trainer (3 years), ESL Instructor (2 years)',
                'graduation_school' => 'Ateneo de Manila University',
                'certification' => 'TESOL, TOEIC 990',
                'about_me' => 'I enjoy playing basketball on weekends. I can help you master the key phrases needed for global business meetings.',
                'specialty' => 'Business English, Pronunciation Training, TOEIC Preparation',
                'rating_average' => 4.88,
            ],
            [
                'first_name' => 'Grace',
                'last_name' => 'Villanueva',
                'email' => 'grace.v@example.com',
                'gender' => 'Female',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400',
                'biography' => 'Patient, enthusiastic, and dedicated to helping beginners build confidence from day one.',
                'point_consumed' => 80,
                'career' => 'ESL Instructor (1 year)',
                'graduation_school' => 'University of San Carlos',
                'certification' => 'TESOL',
                'about_me' => 'I am a big fan of Japanese culture, music, and anime. Let us talk about our favorite topics!',
                'specialty' => 'Beginner English, Free Talk',
                'rating_average' => 4.75,
            ],
            [
                'first_name' => 'Mark Anthony',
                'last_name' => 'Garcia',
                'email' => 'mark.garcia@example.com',
                'gender' => 'Male',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
                'biography' => 'Certified Callan Method trainer focused on building quick speaking reflexes, sentence structure, and fluency.',
                'point_consumed' => 100,
                'career' => 'Language School Instructor (5 years)',
                'graduation_school' => 'De La Salle University',
                'certification' => 'TESOL, CELTA',
                'about_me' => 'I enjoy playing acoustic guitar and reading historical fiction. My goal is to make every lesson structured and productive.',
                'specialty' => 'Callan Method, Grammar Building, IELTS Preparation',
                'rating_average' => 4.92,
            ],
            [
                'first_name' => 'Kristine',
                'last_name' => 'Cruz',
                'email' => 'kristine.cruz@example.com',
                'gender' => 'Female',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400',
                'biography' => 'Extensive experience in teaching young learners using interactive games, phonics, and storytelling.',
                'point_consumed' => 100,
                'career' => 'Early Childhood Educator (2 years), Online ESL Teacher (3 years)',
                'graduation_school' => 'Cebu Normal University (College of Education)',
                'certification' => 'TEYL, Licensed Professional Teacher',
                'about_me' => 'Baking treats and drawing are my passions. I look forward to bringing smiles and energy into every class!',
                'specialty' => 'Kids English, Phonics, Elementary Conversation',
                'rating_average' => 4.90,
            ],
            [
                'first_name' => 'Angelo',
                'last_name' => 'Bautista',
                'email' => 'angelo.b@example.com',
                'gender' => 'Male',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
                'biography' => 'Specializes in news article discussions and topical debate, helping students expand their vocabulary and express nuanced opinions.',
                'point_consumed' => 100,
                'career' => 'English Instructor (3 years)',
                'graduation_school' => 'University of Santo Tomas',
                'certification' => 'TESOL',
                'about_me' => 'I love cafe hopping and street photography. Let us have insightful conversations on current trends and culture.',
                'specialty' => 'News Discussion, Intermediate & Advanced Free Talk',
                'rating_average' => 4.82,
            ],
            [
                'first_name' => 'Bea Joy',
                'last_name' => 'Mendoza',
                'email' => 'bea.mendoza@example.com',
                'gender' => 'Female',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400',
                'biography' => 'Known for clear pronunciation and constructive feedback. I ensure a comfortable, mistake-friendly environment for all learners.',
                'point_consumed' => 100,
                'career' => 'Online ESL Instructor (2 years)',
                'graduation_school' => 'Silliman University',
                'certification' => 'TESOL',
                'about_me' => 'Yoga and mountain hiking keep me grounded. I am eager to help you achieve your learning milestones.',
                'specialty' => 'Travel English, Daily Conversation, Listening Skills',
                'rating_average' => 4.86,
            ],
            [
                'first_name' => 'Rafael',
                'last_name' => 'Navarro',
                'email' => 'rafael.n@example.com',
                'gender' => 'Male',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
                'biography' => 'Pronunciation specialist focusing on intonation, mouth placement, and natural sentence rhythm.',
                'point_consumed' => 120,
                'career' => 'Speech & Accent Trainer (4 years)',
                'graduation_school' => 'Far Eastern University',
                'certification' => 'TESOL, English Phonetics Diploma',
                'about_me' => 'I enjoy voice acting and watching classic cinema. Let us work together on sounding natural and clear.',
                'specialty' => 'Accent Reduction, Speaking Fluency, Intonation',
                'rating_average' => 4.96,
            ],
            [
                'first_name' => 'Princess',
                'last_name' => 'Dela Cruz',
                'email' => 'princess.dc@example.com',
                'gender' => 'Female',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
                'biography' => 'Energetic and friendly tutor focused on boosting speaking confidence and making daily conversations effortless.',
                'point_consumed' => 80,
                'career' => 'Online ESL Teacher (1 year)',
                'graduation_school' => 'Polytechnic University of the Philippines',
                'certification' => 'TESOL',
                'about_me' => 'I love cooking local delicacies and modern dance. I make sure every session is engaging and fun!',
                'specialty' => 'Casual Conversation, Kids English, Vocabulary Building',
                'rating_average' => 4.78,
            ],
            [
                'first_name' => 'Christian',
                'last_name' => 'Alcantara',
                'email' => 'christian.a@example.com',
                'gender' => 'Male',
                'nationality' => 'Philippines',
                'profile_image' => 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
                'biography' => 'Specializes in executive presentation training, business correspondence, and intensive TOEIC prep.',
                'point_consumed' => 150,
                'career' => 'Corporate English Training Specialist (6 years)',
                'graduation_school' => 'University of the Philippines Diliman',
                'certification' => 'TESOL, TOEIC 990',
                'about_me' => 'Passionate about chess and software programming. I take a structured, goal-oriented approach to language learning.',
                'specialty' => 'TOEIC Preparation, Presentation Skills, Executive Business',
                'rating_average' => 4.98,
            ],
        ];

        foreach ($teachers as $teacher) {
            // 1. Insert into users table
            $userId = DB::table('users')->insertGetId([
                'first_name'        => $teacher['first_name'],
                'last_name'         => $teacher['last_name'],
                'role_id'           => 2,
                'email'             => $teacher['email'],
                'phone_number'      => '09' . rand(100000000, 999999999),
                'profile_image'     => $teacher['profile_image'],
                'nationality'       => $teacher['nationality'],
                'gender'            => $teacher['gender'],
                'status'            => 'active',
                'email_verified_at' => now(),
                'password'          => Hash::make('password123'),
                'created_at'        => now(),
                'updated_at'        => now(),
            ]);

            // 2. Insert into teachers table
            DB::table('teachers')->insert([
                'user_id'           => (string)$userId,
                'biography'         => $teacher['biography'],
                'point_consumed'    => $teacher['point_consumed'],
                'career'            => $teacher['career'],
                'graduation_school' => $teacher['graduation_school'],
                'certification'     => $teacher['certification'],
                'about_me'          => $teacher['about_me'],
                'specialty'         => $teacher['specialty'],
                'rating_average'    => $teacher['rating_average'],
                'created_at'        => now(),
                'updated_at'        => now(),
            ]);
        }
    }
}
